default: &default
  host: "redis"
  port: "6379"
  timeout: "60000"
  password: ""
  redisEntityPrefixes:
    agentSchemaPrefix: "test_measurement_result_schema"
    sessionLifecyclePrefix: "session_lifecycle_event"
    agentTestStagesConfigPrefix: "agent_test_stages_config"

development:
  <<: *default
  host: "10.195.176.111"
  port: "30780"
  password: "admin"

staging:
  <<: *default
  host: "redis.infra.svc.cluster.local"
  port: "6379"
  password: "admin"

local:
  <<: *default
  host: "10.195.176.111"
  port: "30780"
  password: "admin"
